spring:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5433/loginRedesNeuronales
    username: postgres
    password: peru2020
    driver-class-name: org.postgresql.Driver
server:
  port: 3010